services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/index.html:/app/index.html
    environment:
      - VITE_API_URL=http://localhost:3001/api
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./server/src:/app/src
    environment:
      - PORT=3001
      - NODE_ENV=development
      - JWT_SECRET=dev-jwt-secret
      - JWT_EXPIRES_IN=1h
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=local
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    ports:
      - "8000:8000"
    volumes:
      - ~/dev/cs5224/dynamodb-data:/data
